name: genai-cpu
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11 
  - jupyterlab 
  - pytorch 
  - torchvision 
  - torchaudio 
  - huggingface_hub 
  - diffusers 
  - transformers 
  - accelerate 
  - anthropic 
  - openai 
  - langchain 
  - stackview 
  - voila 
  - pandas 
  - torchmetrics 
  - scikit-learn 
  - seaborn
  - pip
  - pip:
      - python-pptx 
      - bia-bob 
      - blablado 
      - llama-index 
      - google-generativeai 
      - pygithub
      - opencv-python
      - pooch
      - azure-ai-inference
      - mistralai
      - autogen-core==0.4.0.dev11
      - autogen-agentchat==0.4.0.dev11
      - autogen-ext==0.4.0.dev11
      - llama-index-llms-ollama
      - llama-index-llms-openai-like
      - llama-index-embeddings-huggingface
      - tokenizers==0.21.0
      - pypdf
      - smolagents==1.0.0
prefix: C:\Users\haase\miniconda3\envs\genai-cpu
